sudo: required
services:
  - docker

before_install:
  - docker build -t sreekrishnadutta/docker_repo -f Dockerfile.dev .

script:
  - docker run sreekrishnadutta/docker_repo npm run test -- --coverage

